name: check-pull-request-to-main
run-name: Checking Pull Request to main branch
on:
	pull_request:
		types: [opened, reopened]
	branches:
		- "main"
jobs:
	check-pull-request-to-main:
		runs-on: ubuntu-latest
		steps:
			-name: Checking Pull Request
				if: github.base_ref == 'main' && github.head_ref != 'develop'
				- uses: actions/github-script@v7
						with:
							script: |
								core.setFailed('Pull Request failed. You can only merge to main from develop.')
