name: Check Pull Request to main
run-name: Checking Pull Request to main branch
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - "main"
jobs:
  check-pull-request-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Pull Request
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1
